const list = [
    {"label":"Aryan Aswani","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Prateek Mishra","Title of your Project (in 8 words or less)":"Logic in Computer Science"},
    {"label":"Aadarsh Agarwal","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Aakanksha Jain","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Aakarsh Chaudhary","Title of your Project (in 8 words or less)":"Quantum Computing, Information and Quantum Technologies"},
    {"label":"Aarushi Agarwal","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Aashish Tripathy","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Aastha Sharma","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Aayushman Sinha","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Abdul Raheem K","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Abhay Gupta","Title of your Project (in 8 words or less)":"Digital Signal Processing"},
    {"label":"Abhay Kinagi","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Abhijeet jha","Title of your Project (in 8 words or less)":"Network Security"},
    {"label":"Abhijeet Pal","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Abhiruchi Kotamkar","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"Abhishek Malyan","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Adarsh Reddy Madur","Title of your Project (in 8 words or less)":"Stellar Astrophysics"},
    {"label":"Adbhut Vipin Bhardwaj","Title of your Project (in 8 words or less)":"Macroeconomics"},
    {"label":"Aditya Agrawal","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"ADITYA BYJU","Title of your Project (in 8 words or less)":"Algorithmic Trading"},
    {"label":"Aditya Kumar","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"aditya laddha","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Aditya Mehta","Title of your Project (in 8 words or less)":"Band structure of graphene using Tight-Binding model"},
    {"label":"Aditya Sanjog Kabare","Title of your Project (in 8 words or less)":"Special and General Relativity"},
    {"label":"Aditya Sugriv Kendre","Title of your Project (in 8 words or less)":"Comparing Random Forest Classifier and Neural Networks"},
    {"label":"Agamjot Singh","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Agrim Gupta","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Ajinkya Satishkumar Patil","Title of your Project (in 8 words or less)":"Nonlinear Dynamics"},
    {"label":"Akanksha Singh","Title of your Project (in 8 words or less)":"Quantum Physics"},
    {"label":"Akshat Agarwal","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Akshay Sharma","Title of your Project (in 8 words or less)":"Computational Fluid Dynamics"},
    {"label":"Alapati Tharaka Rama Chowdary","Title of your Project (in 8 words or less)":"Condensed Matter Physics"},
    {"label":"Alfia Zareen Khan","Title of your Project (in 8 words or less)":"Cell Division and Cancer cells"},
    {"label":"Alisha","Title of your Project (in 8 words or less)":"Computational Neuroscience"},
    {"label":"Alok Kumar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Aman Kumar Vishwakarma","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Aman Singh","Title of your Project (in 8 words or less)":"Modern Stock Trading"},
    {"label":"Ameya Deshmukh","Title of your Project (in 8 words or less)":"Abstract Algebra"},
    {"label":"Ameya Halarnkar","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Ameya Marakarkandy","Title of your Project (in 8 words or less)":"Spaceflight Mechanics"},
    {"label":"Ameya Vikrama Singh","Title of your Project (in 8 words or less)":"Combinatorial Game Theory"},
    {"label":"Amisha Saini","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Amit Kumar Jha","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Amruta Deo","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Anagha Bhangare","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Anand Narasimhan","Title of your Project (in 8 words or less)":"Group Theory"},
    {"label":"Anannay jain","Title of your Project (in 8 words or less)":"Stock market Analysis"},
    {"label":"Ananya Dhale","Title of your Project (in 8 words or less)":"Immunology"},
    {"label":"Aneesh Kamat","Title of your Project (in 8 words or less)":"Quantum Computation"},
    {"label":"Angotu Jathin Sai Ganesh","Title of your Project (in 8 words or less)":"STOCK MARKET ANALYSIS"},
    {"label":"Aniket Chandrakant Warungse","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Aniket Zambare","Title of your Project (in 8 words or less)":"Quantum Mechanics"},
    {"label":"Animesh Sahoo","Title of your Project (in 8 words or less)":"Robotics and Controls"},
    {"label":"Anish Amol Kulkarni","Title of your Project (in 8 words or less)":"Topology"},
    {"label":"Anisha Basumatary","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Ankit Kumar","Title of your Project (in 8 words or less)":"Economics: Micro & Macro"},
    {"label":"Ankit Somani","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Ankith R","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"Ankur Kumar","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Anmol Kumar Sharma","Title of your Project (in 8 words or less)":"Machine Design"},
    {"label":"Annirudh K P","Title of your Project (in 8 words or less)":"Probability and Statistics"},
    {"label":"Anubhav Bhatla","Title of your Project (in 8 words or less)":"Operating Systems"},
    {"label":"Anuj Bhawsar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Anuja Sanjay Sathe","Title of your Project (in 8 words or less)":"Robotics with Arduino UNO"},
    {"label":"Anupsa Swain","Title of your Project (in 8 words or less)":"Rock, Paper, Scissors: Three Players Edition"},
    {"label":"Anurag Chaudhari","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Anushka Nalawade","Title of your Project (in 8 words or less)":"Data Structures & Algorithms"},
    {"label":"Apoorva Kanti","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Apurv Keer","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Archit Gupta","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Areeb Asgar","Title of your Project (in 8 words or less)":"Operating Systems"},
    {"label":"Arhaan Ahmad","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Arham Jain","Title of your Project (in 8 words or less)":"Modern stock trading"},
    {"label":"Arnab Mondal","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Arnav Pandit","Title of your Project (in 8 words or less)":"Conumer Theory and Behavioral Analysis"},
    {"label":"Arnav Patel","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Arpita Kumari","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Arush Gaur","Title of your Project (in 8 words or less)":"Solar Thermal Power Plants"},
    {"label":"Arya Agarwal","Title of your Project (in 8 words or less)":"STOCK MARKET ANALYSIS"},
    {"label":"Aryan Biswas","Title of your Project (in 8 words or less)":"Stock market analysis"},
    {"label":"aryan chourasia","Title of your Project (in 8 words or less)":"Game theory"},
    {"label":"Aryan Gupta","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Aryan kumar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Aryant Balot","Title of your Project (in 8 words or less)":"Heat Transfer"},
    {"label":"Ashish Kedari","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Ashish Singh Chauhan","Title of your Project (in 8 words or less)":"Blockchain Technologies"},
    {"label":"Ashok Kumar","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Ashrita Vegi","Title of your Project (in 8 words or less)":"Consumer Theory and Behavioral Analysis"},
    {"label":"Ashutosh Singh","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Ashutosh Yadav","Title of your Project (in 8 words or less)":"Date Fruits Classification Accuracy"},
    {"label":"Ashwin Abraham","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Ashwin Goyal","Title of your Project (in 8 words or less)":"Newtonian Orbital Dynamics"},
    {"label":"Astha Maurya","Title of your Project (in 8 words or less)":"Heuristic Approach: Real Analysis"},
    {"label":"Atharv Ramakant Nemade","Title of your Project (in 8 words or less)":"modern stock trading"},
    {"label":"Atharva Arora","Title of your Project (in 8 words or less)":"Special Relativity"},
    {"label":"Atharva Sunil Bagade","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Atishay Jain","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Ayan Mallick","Title of your Project (in 8 words or less)":"Cosmology and Dark matter"},
    {"label":"AYUSH AGARWAL","Title of your Project (in 8 words or less)":"Data Structure & Algorithm"},
    {"label":"Ayush Kapoor","Title of your Project (in 8 words or less)":"Data Structure & Algorithm"},
    {"label":"Ayush Patil","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"AYUSH SAHU","Title of your Project (in 8 words or less)":"stock market analysis"},
    {"label":"Ayush Tarway","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Ayushh","Title of your Project (in 8 words or less)":"Big Data"},
    {"label":"Ayushman Choudhary","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"Aziz Shameem","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Badal Varshney","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Besekar Vaibhav Sudhakar","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Bhaskar Pegu","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Bhavana P","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Bhavesh Khichi","Title of your Project (in 8 words or less)":"Robotics"},
    {"label":"Bhawna Bharti","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Bhawna Mahur","Title of your Project (in 8 words or less)":"Deep Learning and Neural Network"},
    {"label":"Bhumika Bhangale","Title of your Project (in 8 words or less)":"Machines and materials"},
    {"label":"Bhuvana Chandra Pullabhotla","Title of your Project (in 8 words or less)":"Control Theory"},
    {"label":"Bijay Kumar Shah","Title of your Project (in 8 words or less)":"Deep Learning and Neural Network"},
    {"label":"bijja sai kalyan","Title of your Project (in 8 words or less)":"study of cosmology and dark matter"},
    {"label":"Chaitanya Aggarwal","Title of your Project (in 8 words or less)":"An Introduction to Algorithmic Trading"},
    {"label":"Chanakya Varude","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Chandan Soni","Title of your Project (in 8 words or less)":"Deep Learning"},
    {"label":"Charel Jaykumar Kanjibhai","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Charul Mittal","Title of your Project (in 8 words or less)":"Social Market Analysis"},
    {"label":"Cheerla Vinay Kumar","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"cheshta damor","Title of your Project (in 8 words or less)":"data science"},
    {"label":"Chetan Patil","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Chinmay Makarand Pimpalkhare","Title of your Project (in 8 words or less)":"Graph Theory"},
    {"label":"Chinta Siva Madhav","Title of your Project (in 8 words or less)":"Celestial Mechanics"},
    {"label":"Chirag S","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Dadi Dharani","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Daksh Jain","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Daniel Gracias","Title of your Project (in 8 words or less)":"Nanomaterials"},
    {"label":"Darshan Kumar","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Darshan Makwana","Title of your Project (in 8 words or less)":"Neural Networks"},
    {"label":"Debasish Panda","Title of your Project (in 8 words or less)":"Device Physics"},
    {"label":"DEEPAK KUMAR","Title of your Project (in 8 words or less)":"GROUP THEORY"},
    {"label":"Deepankar Sehra","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Dendukuri Sandeep Varma","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Devang Agarwal","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Devanshu Saraf","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Dhavalkant","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Dhawal Singh","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Dhruv Piyush Rambhia","Title of your Project (in 8 words or less)":"Stochastic Processes"},
    {"label":"Dhruvi Ganatra","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Dipanshu Srivastava","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Divyanshu rathore","Title of your Project (in 8 words or less)":"Data structure and algorithms"},
    {"label":"Dosapati Jayanth","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"G Kamalesh","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Gaurav Maheshwari","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Gaurav Shirsath","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Gaurav soni","Title of your Project (in 8 words or less)":"Data Structure And Algorithm"},
    {"label":"Gaurishankar Swain","Title of your Project (in 8 words or less)":"Network Security"},
    {"label":"Gautam Asodiya","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Gautam Prabhudesai","Title of your Project (in 8 words or less)":"Biotechnology and Biophysics"},
    {"label":"Gehna Gudhainia","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Gourish Singhal","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Govind Kumar","Title of your Project (in 8 words or less)":"Quantum Computing, Information, and Quantum Technology"},
    {"label":"Hardik Batra","Title of your Project (in 8 words or less)":"Principles Of Mathematical Analysis"},
    {"label":"Hardik Panchal","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Harsh Agarwal","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Harsh Amit  Shah","Title of your Project (in 8 words or less)":"Reinforcement Learning"},
    {"label":"Harsh Chaurasia","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"Harsh Hitesh Shah","Title of your Project (in 8 words or less)":"Mechanics and Materials"},
    {"label":"Harsh Vardhan","Title of your Project (in 8 words or less)":"STOCK MARKET AND ANALYSIS"},
    {"label":"Harshini Sreeram","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Harshit Dandelia","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Harshit Porwal","Title of your Project (in 8 words or less)":"Modern Stock Trading"},
    {"label":"Harshit Raj","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Harshit Upadhyay","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Harshvardhan","Title of your Project (in 8 words or less)":"Data Science with ML/AI"},
    {"label":"Harsitha Devaraj","Title of your Project (in 8 words or less)":"Introduction to Stock Market"},
    {"label":"Himani Tamrakar","Title of your Project (in 8 words or less)":"Data Structures and algorithms"},
    {"label":"Himanshu Kumar","Title of your Project (in 8 words or less)":"STOCK MARKET ANALYSIS"},
    {"label":"Himanshu Raj","Title of your Project (in 8 words or less)":"Fluid Mechanics"},
    {"label":"Hiranmai Mohan","Title of your Project (in 8 words or less)":"Nanomaterials"},
    {"label":"Hrishikesh Jedhe Deshmukh","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Isha Arora","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Isha Dev","Title of your Project (in 8 words or less)":"Consumer Theory and Behavioral Economics"},
    {"label":"Ishaan Garg","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"Ishaanvi Agrawal","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Ishan Jain","Title of your Project (in 8 words or less)":"Computational Fluid Dynamics"},
    {"label":"Ishan Rajani","Title of your Project (in 8 words or less)":"Algorithmic Trading"},
    {"label":"Ishan Upadhyay","Title of your Project (in 8 words or less)":"Reinforcement Learning"},
    {"label":"Ishita Poddar","Title of your Project (in 8 words or less)":"Consumer Theory and Behavioural Economics"},
    {"label":"Ishwari Solase","Title of your Project (in 8 words or less)":"Probability and Statistics"},
    {"label":"Jagruti Lahamge","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Jagruti Lahamge","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Jagruti Lahamge","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"jahnvee tailor","Title of your Project (in 8 words or less)":"special theory of relativity"},
    {"label":"Jahnvi Singh Rohela","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Jaideep Kotani","Title of your Project (in 8 words or less)":"Operating Systems"},
    {"label":"Jainesh Manish Mehta","Title of your Project (in 8 words or less)":"Quantum Information and Computing"},
    {"label":"Janhavi Sonawane","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Jaskeerat Kaur Billing","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"jayansh rangwani","Title of your Project (in 8 words or less)":"BlockChain Technology"},
    {"label":"Jayatri Pati","Title of your Project (in 8 words or less)":"Bioinformatics"},
    {"label":"JAYESH BHAGWAN BAGUL","Title of your Project (in 8 words or less)":"QUANTUM INFORMATION &  COMPUTING"},
    {"label":"Jayveer Singh Sikarwar","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"Jenil Dayma","Title of your Project (in 8 words or less)":"Economics"},
    {"label":"Jennisha Agrawal","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Josyula Venkata Aditya","Title of your Project (in 8 words or less)":"Quantum Computing, Information and Quantum Technology"},
    {"label":"Kabir Bajaj","Title of your Project (in 8 words or less)":"Analytical Formulation of Classical Field Theory"},
    {"label":"Kalyani Gattani","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Kamble Bipin Ganpati","Title of your Project (in 8 words or less)":"corporate finance"},
    {"label":"Kandarp Solanki","Title of your Project (in 8 words or less)":"Data Structures & Algorithms"},
    {"label":"Kanishk Malkan","Title of your Project (in 8 words or less)":"Number Theory"},
    {"label":"Karan","Title of your Project (in 8 words or less)":"Corporate finance"},
    {"label":"Karan Godara","Title of your Project (in 8 words or less)":"GAME THEORY"},
    {"label":"Kartik Nair","Title of your Project (in 8 words or less)":"Information Theory"},
    {"label":"Kartik Sood","Title of your Project (in 8 words or less)":"STOCK MARKET ANALYSIS FOR INVESTING"},
    {"label":"Kartikey Anand","Title of your Project (in 8 words or less)":"Deep Learning"},
    {"label":"Kaushal Kumar Khunteta","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Kaushikraj Maharajan","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"Kaustav Prasad","Title of your Project (in 8 words or less)":"Photonics and Quantum Optics"},
    {"label":"Kavita Chouhan","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Kedar Desai","Title of your Project (in 8 words or less)":"Image Processing"},
    {"label":"Keshav Patel Keval","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Khushal Kumawat","Title of your Project (in 8 words or less)":"Data science"},
    {"label":"Khushang Singla","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Khushi Sagar","Title of your Project (in 8 words or less)":"Fundamentals of Corporate Finance"},
    {"label":"Khyathi Mothika","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Kirtan Bhaskar","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Komalika Shirud","Title of your Project (in 8 words or less)":"Data structures and algorithms"},
    {"label":"Krishna Sirra","Title of your Project (in 8 words or less)":"Diving into Machine Learning : Deep Learning."},
    {"label":"krithika mittal","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Kritika Gupta","Title of your Project (in 8 words or less)":"Prediction Using Regression Models"},
    {"label":"Kumari Pragati Gupta","Title of your Project (in 8 words or less)":"Digital Image Processing"},
    {"label":"Kumkum Narang","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Kunal","Title of your Project (in 8 words or less)":"Probability and Statistics"},
    {"label":"Kunal Kailash Sharma","Title of your Project (in 8 words or less)":"Computational Fluid Dynamics"},
    {"label":"Kunal Kumar Singh","Title of your Project (in 8 words or less)":"Automotive Design"},
    {"label":"Kushal Agarwal","Title of your Project (in 8 words or less)":"Spaceflight Mechanics"},
    {"label":"Kushal Pawaskar","Title of your Project (in 8 words or less)":"Operating Systems"},
    {"label":"Lavanya Raj","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Maalavika C S","Title of your Project (in 8 words or less)":"Immunology"},
    {"label":"Madhav Gupta","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Mahesh K","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Mainak Singha","Title of your Project (in 8 words or less)":"Auto Image Captioning"},
    {"label":"Maithri Suresh","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Mali Shwetambari Sanjay","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Malyala Preethi Sravani","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Manali Mandar Manjarekar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Manan Garg","Title of your Project (in 8 words or less)":"Operating Systems"},
    {"label":"Manas Nagda","Title of your Project (in 8 words or less)":"Elementary Particle Physics"},
    {"label":"Manasi Pawar","Title of your Project (in 8 words or less)":"Data Science and Neural Networks"},
    {"label":"Manaswi Dhurve","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Manish kumar","Title of your Project (in 8 words or less)":"Data science"},
    {"label":"Mehul Vijay Chanda","Title of your Project (in 8 words or less)":"Electronics And Instrumentation"},
    {"label":"Modi Jay Kalpeshkumar","Title of your Project (in 8 words or less)":"Biotechnology and Biophysics"},
    {"label":"Mohd Saif","Title of your Project (in 8 words or less)":"Hydrogen Storage and Its Utility"},
    {"label":"MOHD SHADAB ANSARI","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Mohit Punasiya","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"Moiz Shakruwala","Title of your Project (in 8 words or less)":"Deep Learning and Neural and Neural Networks"},
    {"label":"Moneesha PB","Title of your Project (in 8 words or less)":"ECONOMICS"},
    {"label":"Moningi Srija","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Mridul Agarwal","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Naman Singh Rana","Title of your Project (in 8 words or less)":"ML Applications in Biology"},
    {"label":"Namita Agarwal","Title of your Project (in 8 words or less)":"Quantum Field Theory"},
    {"label":"Nandini beflawat","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"Navdha","Title of your Project (in 8 words or less)":"Cosmology and Dark matter"},
    {"label":"Niare Doyom","Title of your Project (in 8 words or less)":"Deep Dive into Quantum Information and technology"},
    {"label":"Nikhil Kumar","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"Nikita Sharma","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Nilabha Saha","Title of your Project (in 8 words or less)":"Quantum Computing and Information"},
    {"label":"Nilabja Mandal","Title of your Project (in 8 words or less)":"Fundamentals of Financial Mathematics: Modern Portfolio Theory in Brief"},
    {"label":"Niranjan Deori","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Nishant Thakre","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Nishika Tolambiya","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Nitish Goel","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Nupur Unavekar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Ojas Karanjkar","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Ojasvi Kathuria","Title of your Project (in 8 words or less)":"Game theory"},
    {"label":"Om Joglekar","Title of your Project (in 8 words or less)":"PnC"},
    {"label":"Om Katke","Title of your Project (in 8 words or less)":"How Sorting in Linked Lists is done by MergeSort?"},
    {"label":"Om Unhale","Title of your Project (in 8 words or less)":"Robotics (Drone making)"},
    {"label":"Omar Kashmar","Title of your Project (in 8 words or less)":"Machine Learning Algorithms"},
    {"label":"Pal Aggarwal","Title of your Project (in 8 words or less)":"Psychology"},
    {"label":"Palak Vora","Title of your Project (in 8 words or less)":"Nanotechnology in medicine"},
    {"label":"PARAM SHAH","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Parishi Gupta","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Parivesh meena","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Patel Hemali Sureshbhai","Title of your Project (in 8 words or less)":"Web Developement"},
    {"label":"Pathipati Girishma Chowdary","Title of your Project (in 8 words or less)":"Probability and Statistics"},
    {"label":"Pavan Vijay Bodke","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Pawan Kumar Meena","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Peram Ankshitha","Title of your Project (in 8 words or less)":"MACHINE LEARNING"},
    {"label":"Piyush Choudhary","Title of your Project (in 8 words or less)":"Fundamentals of Quantitative Analysis"},
    {"label":"Piyush Mourya","Title of your Project (in 8 words or less)":"Machine Design"},
    {"label":"Pooja Shelar","Title of your Project (in 8 words or less)":"Machine learning- Deep learning"},
    {"label":"Poojita Mishra","Title of your Project (in 8 words or less)":"Stock market Analysis"},
    {"label":"Pothala Sowmyasri","Title of your Project (in 8 words or less)":"PROBABILITY AND STATISTICS"},
    {"label":"Pradnya Manoj Kumbhare","Title of your Project (in 8 words or less)":"Reinforcement learning"},
    {"label":"Prakhar Tiwari","Title of your Project (in 8 words or less)":"Automobile Design"},
    {"label":"Prakriti Shahi","Title of your Project (in 8 words or less)":"Quantum Computing, Information and Quantum Technologies"},
    {"label":"Pranali Sarvade","Title of your Project (in 8 words or less)":"Vitamin B12 Synthesis"},
    {"label":"Pranav Sambhare","Title of your Project (in 8 words or less)":"Reinforcement Learning"},
    {"label":"Pranav Singla","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Prasad Chaure","Title of your Project (in 8 words or less)":"Theory of relativity"},
    {"label":"Prasenjit Darole","Title of your Project (in 8 words or less)":"Blockchain Technology (Intro to DApp)"},
    {"label":"Prashant Ranjan","Title of your Project (in 8 words or less)":"Web development"},
    {"label":"Pratham Chandra","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Pratham Tarjule","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Prathamesh Deshmukh","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Prathmesh Arvind Shimpi","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Praveen Saharan","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Prayaag Desai","Title of your Project (in 8 words or less)":"Mathematical Modeling of Financial Risk Management"},
    {"label":"Prerak Contractor","Title of your Project (in 8 words or less)":"Quantum Information and Computing"},
    {"label":"Prerna Agrawal","Title of your Project (in 8 words or less)":"Gravity Assist Flybys"},
    {"label":"Prince kumar","Title of your Project (in 8 words or less)":"Data Structure and Algorithm in C++"},
    {"label":"Priyadarshini Kamat","Title of your Project (in 8 words or less)":"Criminology"},
    {"label":"Priyam Garg","Title of your Project (in 8 words or less)":"Consumer Theory"},
    {"label":"Priyansh Gopawat","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Priyanshi Gupta","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Priyanshu Gupta","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Priyanshu Saini","Title of your Project (in 8 words or less)":"Nuclear Reactor"},
    {"label":"Puja Maitra","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Purusotam Mishra","Title of your Project (in 8 words or less)":"Web Development"},
    {"label":"Raghav Rander","Title of your Project (in 8 words or less)":"General Astronomy"},
    {"label":"Raghav Rawat ","Title of your Project (in 8 words or less)":"Overview of computer vision"},
    {"label":"Raghav Rawat","Title of your Project (in 8 words or less)":"Financial Mathematic"},
    {"label":"Rahul Varma","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Rajadhyaksha Apoorva Girish","Title of your Project (in 8 words or less)":"Immunology in Health and Disease"},
    {"label":"Rajik Kumar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Rakesh Kumar","Title of your Project (in 8 words or less)":"Book recommendation system"},
    {"label":"Ram Kandalkar","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Ram Prakash","Title of your Project (in 8 words or less)":"Quantum physics"},
    {"label":"Ramavath manikanth","Title of your Project (in 8 words or less)":"Algorthmic trading"},
    {"label":"Rathin Asodariya","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Ravi Singh Adhikari","Title of your Project (in 8 words or less)":"Quantum Information And Computing"},
    {"label":"Reddy Bhavana","Title of your Project (in 8 words or less)":"Neural Networks and deep learning"},
    {"label":"Rehmat Singh Chawla","Title of your Project (in 8 words or less)":"Elementary Particle Physics"},
    {"label":"Rishank Suhas Meshram","Title of your Project (in 8 words or less)":"Black hole thermodynamics"},
    {"label":"Ritik Kumar","Title of your Project (in 8 words or less)":"Modern Stock Trading"},
    {"label":"Rucha Manish Aghera","Title of your Project (in 8 words or less)":"Extra-Galactic Astronomy"},
    {"label":"Rushika Shimpi","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Sabyasachi Samantaray","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Sahil Vaidya","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Sainath Vavilapalli","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"Sajal Deolikar","Title of your Project (in 8 words or less)":"Control Theory"},
    {"label":"sakshi agarwal","Title of your Project (in 8 words or less)":"web development"},
    {"label":"Sakshi Priya","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Salil Singhal","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Saloni Kajal","Title of your Project (in 8 words or less)":"Psychology"},
    {"label":"Samagra Jain","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Samar jeet","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"SAMARTH SHARMA","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Sameep Chattopadhyay","Title of your Project (in 8 words or less)":"Information Theory"},
    {"label":"Sameer Kankute","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Samriddhi Mishra","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Samyak Jha","Title of your Project (in 8 words or less)":"Differential Gemometry"},
    {"label":"Sanika Landge","Title of your Project (in 8 words or less)":"Stock market analysis"},
    {"label":"Sanika Wagh","Title of your Project (in 8 words or less)":"Robotics"},
    {"label":"Sanjana Shinde","Title of your Project (in 8 words or less)":"Spaceflight mechanics"},
    {"label":"Sanjhi Priya","Title of your Project (in 8 words or less)":"Consumer Theory and Behavioral Analysis"},
    {"label":"Sanket Kothawade","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Sanket Sanjay Pawar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Sanyam jain","Title of your Project (in 8 words or less)":"modern stock trading"},
    {"label":"Saransh Soni","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Sathvik Kanna","Title of your Project (in 8 words or less)":"Modern Stock Trading"},
    {"label":"Satush Parikh","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Saukhya Telge","Title of your Project (in 8 words or less)":"Spaceflight Mechanics"},
    {"label":"SAURAV KUMAR","Title of your Project (in 8 words or less)":"Basic Control Theory"},
    {"label":"Sehajpal Singh","Title of your Project (in 8 words or less)":"Exoplanets and their detection"},
    {"label":"Shaswat Kumar","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Shirsh Sawarna","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Shiv Kiran Bagathi","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Shiv Nandan Singh","Title of your Project (in 8 words or less)":"Data Structure and Algorithms"},
    {"label":"Shivam Raj","Title of your Project (in 8 words or less)":"Data Structure and Algorithms"},
    {"label":"Shivam Vinod Patil","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Shlesh Gholap","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Shlok zanwar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Shounak Dewoolkar","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Shravya Suresh","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"Shreyas Dayal","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Shreyas N B","Title of your Project (in 8 words or less)":"Black Hole Thermodynamics"},
    {"label":"Shruti Lohar","Title of your Project (in 8 words or less)":"Hydrogen Storage and its Utility"},
    {"label":"Shruti Nandeshwar","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Shubh Verma","Title of your Project (in 8 words or less)":"Game Theory"},
    {"label":"Shubham Gurjar","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"SHUBHAM SINGH RAO","Title of your Project (in 8 words or less)":"Electric Vehicles modeling"},
    {"label":"Shubhang Shanghvi","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Siddhant Gedam","Title of your Project (in 8 words or less)":"Cosmology and dark matter"},
    {"label":"Siddhant Kalel","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Siddharth Anand","Title of your Project (in 8 words or less)":"Coding Theory"},
    {"label":"Simran Sinha","Title of your Project (in 8 words or less)":"Quantum Information and Computing"},
    {"label":"SK TAUSIF PARVEZ","Title of your Project (in 8 words or less)":"Quantum Field Theory"},
    {"label":"Smit Solanki","Title of your Project (in 8 words or less)":"Blockchain Technology"},
    {"label":"Smit Wagh","Title of your Project (in 8 words or less)":"Data Structures And Algorithms"},
    {"label":"Sneha Gaikwad","Title of your Project (in 8 words or less)":"Data structures n algorithms"},
    {"label":"Snehaa Reddy","Title of your Project (in 8 words or less)":"Quantum computing and information"},
    {"label":"Soham Joshi","Title of your Project (in 8 words or less)":"Electronic Properties of Materials"},
    {"label":"Soham Joshi","Title of your Project (in 8 words or less)":"Application of Number Theory in Cryptography"},
    {"label":"Solanki Shreyas","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Sonam M","Title of your Project (in 8 words or less)":"Psychology"},
    {"label":"Soutrik Sarangi","Title of your Project (in 8 words or less)":"Deep Learning and Neural Networks"},
    {"label":"Spandan Sachin Anaokar","Title of your Project (in 8 words or less)":"Introduction to the Special Theory of Relativity"},
    {"label":"Sreetam Tripathy","Title of your Project (in 8 words or less)":"Linear Algebra"},
    {"label":"Srijan Jha","Title of your Project (in 8 words or less)":"DATA STRUCTURES AND ALGORITHMS"},
    {"label":"Sriniketan Joshi","Title of your Project (in 8 words or less)":"Quantum computing and quantum technologies"},
    {"label":"Sthavir Mundre","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Subram Das","Title of your Project (in 8 words or less)":"Computer Vision"},
    {"label":"Sumit Kumar","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Sumit Prasad","Title of your Project (in 8 words or less)":"Data Structures and Algorithms"},
    {"label":"Surabhi Gupta","Title of your Project (in 8 words or less)":"The Probability & Statistics of Finance"},
    {"label":"Swadhin Dash","Title of your Project (in 8 words or less)":"Data structures and Algorithms"},
    {"label":"Tambade Atharv Rhushikesh","Title of your Project (in 8 words or less)":"Group Theory"},
    {"label":"Tamojeet Roychowdhury","Title of your Project (in 8 words or less)":"Special Relativity"},
    {"label":"Tanirika Roy","Title of your Project (in 8 words or less)":"Cryptography"},
    {"label":"Tanmay Jain","Title of your Project (in 8 words or less)":"Blockchain"},
    {"label":"Tanmay Lodha","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Tanmay Madavi","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Tanmay Patil","Title of your Project (in 8 words or less)":"Special and General Theory of Relativity"},
    {"label":"Tanmayee Bhadange","Title of your Project (in 8 words or less)":"Psychology"},
    {"label":"Tayde Indrayani Sadanand","Title of your Project (in 8 words or less)":"Markov Chains and Applications in Finance"},
    {"label":"Tejas Amritkar","Title of your Project (in 8 words or less)":"Image Processing"},
    {"label":"Tejas Neema","Title of your Project (in 8 words or less)":"Understanding Economics"},
    {"label":"Tharun Sidambaram M","Title of your Project (in 8 words or less)":"Redox Flow Batteries and Solid State Batteries"},
    {"label":"Tipparthi Jaideep Chandra","Title of your Project (in 8 words or less)":"Machine Learning"},
    {"label":"Tushnim Yuvaraj","Title of your Project (in 8 words or less)":"Number Theory"},
    {"label":"Umeshkumar Ghaskata","Title of your Project (in 8 words or less)":"Data Structure and Algorithms"},
    {"label":"unnati markam","Title of your Project (in 8 words or less)":"stock market analysis"},
    {"label":"Utkarsh Agiwal","Title of your Project (in 8 words or less)":"Natural Language and Processing"},
    {"label":"Utkarsh Chittora","Title of your Project (in 8 words or less)":"Consumer Theory and Behavioral Economics"},
    {"label":"Utkarsh Gupta","Title of your Project (in 8 words or less)":"Robotics"},
    {"label":"Utkarsha Patil","Title of your Project (in 8 words or less)":"Statistics and Probability"},
    {"label":"Utsav Paliwal","Title of your Project (in 8 words or less)":"stocks"},
    {"label":"Vaibhav Kumar","Title of your Project (in 8 words or less)":"Network Security"},
    {"label":"Vaibhav Ramesh Patil","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Vaishnavi Gawade","Title of your Project (in 8 words or less)":"Consumer Theory And Behavioral Analysis"},
    {"label":"Vaishnavi Shinde","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Varada Jaswanth Naidu","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Varnika Agarwal","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Varun Mattapally","Title of your Project (in 8 words or less)":"Natural Language Processing"},
    {"label":"Vedang Dhirendra Asgaonkar","Title of your Project (in 8 words or less)":"AlgoTrading"},
    {"label":"Vedant Vikas Chandewar","Title of your Project (in 8 words or less)":"Artificial Intelligence"},
    {"label":"Vedika Rathi","Title of your Project (in 8 words or less)":"Special Theory of Relativity"},
    {"label":"Vemparala Lakshmi Pravallika","Title of your Project (in 8 words or less)":"Control Theory and its Applications"},
    {"label":"venkata ganesh paidi","Title of your Project (in 8 words or less)":"GAME THEORY"},
    {"label":"Vibha Karnad","Title of your Project (in 8 words or less)":"Graph theory"},
    {"label":"Vijaya Bala Murugan I","Title of your Project (in 8 words or less)":"MACHINE LEARNING"},
    {"label":"Vinay Sutar","Title of your Project (in 8 words or less)":"Number Theory"},
    {"label":"Vinayak Goyal","Title of your Project (in 8 words or less)":"Algorithmic Trading"},
    {"label":"Vinayak Srivastava","Title of your Project (in 8 words or less)":"Neural Networks and Deep Learning"},
    {"label":"Vipin Singh","Title of your Project (in 8 words or less)":"Algorithmic Trading"},
    {"label":"Vishal Kumar","Title of your Project (in 8 words or less)":"An Introduction to Game Theory"},
    {"label":"Vishwesh Raut","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Vivek Kumar","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Vora Jay Bhaveshbhai","Title of your Project (in 8 words or less)":"Reinforcement Learning"},
    {"label":"Vrinda Goel","Title of your Project (in 8 words or less)":"Data Structures & Algorithms"},
    {"label":"Yabaji Pratik Sanjay","Title of your Project (in 8 words or less)":"Introduction to Machine Leraning"},
    {"label":"Yash Kothari","Title of your Project (in 8 words or less)":"Cracking the Stock Market code"},
    {"label":"Yash Kumar","Title of your Project (in 8 words or less)":"Data Structure and Algorithms"},
    {"label":"Yash Salunkhe","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Yash saraogi","Title of your Project (in 8 words or less)":"Corporate Finance"},
    {"label":"Yash Virani","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Yooktashree Barai","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"","Title of your Project (in 8 words or less)":""},
    {"label":"Abhinav Ghunawat","Title of your Project (in 8 words or less)":"Algorithmic Trading"},
    {"label":"Abhinav Vashishtha","Title of your Project (in 8 words or less)":"Economics"},
    {"label":"Amey Patil","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Ankita Anand","Title of your Project (in 8 words or less)":"Financial mathematics"},
    {"label":"Deepanshu Prasad","Title of your Project (in 8 words or less)":"Stock Market analysis"},
    {"label":"Hardik Jaluthariya","Title of your Project (in 8 words or less)":"Psychology"},
    {"label":"Kulbhushan Paliwal","Title of your Project (in 8 words or less)":"Financial Mathematics"},
    {"label":"Likith B","Title of your Project (in 8 words or less)":"Understanding of Cryptography"},
    {"label":"Mansi Ahire","Title of your Project (in 8 words or less)":"Financial mathematics"},
    {"label":"Mude Yashwanth","Title of your Project (in 8 words or less)":"ML"},
    {"label":"Nandini Chandak","Title of your Project (in 8 words or less)":"Cosmology and Dark Matter"},
    {"label":"Nikhil Thakre","Title of your Project (in 8 words or less)":"Image Processing -decoding the pixels"},
    {"label":"Nishant Rasekar","Title of your Project (in 8 words or less)":"Data Science"},
    {"label":"Ojas Jain","Title of your Project (in 8 words or less)":"Stock Market Analysis"},
    {"label":"Sanjana Nagmoti","Title of your Project (in 8 words or less)":"Organic Synthesis, Synthesis of caffeine"},
    {"label":"Shardul Kher","Title of your Project (in 8 words or less)":"Robotics"},
    {"label":"Sidhant Bose","Title of your Project (in 8 words or less)":"Fundamentals of Computer Vision"}
    ]
export default list